In [44]:
import numpy as np

In [45]:
inputs = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [46]:
def activate(dot,thresh):
    return np.array(list(map(int,dot>=thresh)))

## AND

In [47]:
weights = np.array([1,1])

In [48]:
dot = inputs.dot(weights)

In [49]:
outputs = activate(dot,2)

In [50]:
print(outputs)

[0 0 0 1]


## OR

In [51]:
weights = np.array([1,1])

In [52]:
dot = inputs.dot(weights)

In [53]:
outputs = activate(dot,1)

In [54]:
print(outputs)

[0 1 1 1]


## NAND

In [55]:
weights = np.array([-1,-1])

In [56]:
dot = inputs.dot(weights)

In [57]:
outputs = activate(dot,-1)

In [58]:
print(outputs)

[1 1 1 0]


## NOR

In [59]:
weights = np.array([-1,-1])

In [60]:
dot = inputs.dot(weights)

In [61]:
outputs = activate(dot,0)

In [62]:
print(outputs)

[1 0 0 0]
